// --------------------------------------------------------------
// -                      Monster  Scripts                      -
// --------------------------------------------------------------

npc: npc_myro/mobs/jail.txt
npc: npc_myro/mobs/pvp.txt
npc: npc_myro/mobs/towns.txt
