// --------------------------------------------------------------
//  myro custom scripts (overrides npc/scripts_custom.conf)
// --------------------------------------------------------------
//  Enable by uncommenting or adding a line:
//  npc: npc_myro/custom/xxx.txt
//  (script files must be GBK encoded)

npc: npc_myro/custom/son.txt
